spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_center?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 159753
  application:
    name: usercenter-core-service
  rabbitmq:
    host: localhost
    username: user
    password: 123456
    port: 5672
dubbo:
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
    timeout: 10000
  protocol:
    name: dubbo
    port: 30004
server:
  port: 8080
uc:
  redis:
      host: 127.0.0.1:6379
      timeout: 5s
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_

